core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from core.models import *
from core.views import *
from django.conf import settings


urlpatterns = patterns('',
        (r'^$', index),
        (r'^project/(?P<project_id>\d+)/ticket/new/$', add_or_update_ticket,{},'add_ticket_url'),
        (r'^project/(?P<project_id>\d+)/ticket/(?P<ticket_id>\d+)/update/$', add_or_update_ticket,{},'update_ticket_url'),
        (r'^project/(?P<project_id>\d+)/ticket/(?P<object_id>\d+)/add_related_ticket/$',add_related_ticket,{},'add_related_ticket_url'),
        (r'^project/(?P<project_id>\d+)/news/(?P<object_id>\d+)/$',news_detail,{}, 'news_detail_url'),
        (r'^project/(?P<project_id>\d+)/ticket/(?P<object_id>\d+)/$',ticket_detail,{},"ticket_detail_url"),
        (r'^project/(?P<object_id>\d+)/news/new/$',add_news,{},'add_news_url'),
        (r'^project/(?P<object_id>\d+)/news/$',news, {}, "news_url"),
        (r'^project/(?P<object_id>\d+)/$', project_detail,{},"project_detail_url"),
        (r'^project/(?P<object_id>\d+)/repository$',project_repository,{},"project_repository_url"),
        (r'^projects/$', projects,{},"project_list_url"),
        (r'^search/$', search, {}, 'search_url'),
)

urls.py
from django.conf.urls.defaults import *
from core import urls
from core import views
from django.contrib import admin
from django.conf import settings


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^',include('core.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^search/', "core.views.custom_search_view", {}, 'search_url'),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^accounts/logout/$',"django.contrib.auth.views.logout",{'next_page' : '/'}),
    (r'^accounts/', include('registration.urls')),
    (r'^attachments/', include('attachments.urls')),
)

if settings.LOCAL_DEV:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root' : settings.MEDIA_ROOT}),
    )

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.core.mail import EmailMessage
from django.utils.translation import ugettext_lazy as _
from django.template.loader import get_template, render_to_string
from django.template import Context
from django_extensions.db.models import TimeStampedModel
from django.conf import settings
from object_permissions.models import ObjectPermission
import django_filters

class ProjectManager(models.Manager):
    def for_user(self, user):
        '''
        Returns queryset with projects that user can_view (in case of admin - all projects)
        '''
        qs = self.get_query_set()
        if not user.is_superuser:
            qs = self.get_query_set().filter(permissions__user=user,permissions__can_view=True)
        return qs

class Project(TimeStampedModel):
    name = models.CharField(max_length=50, verbose_name=_('name'))
    description = models.TextField(verbose_name=_('description'))
    repository_path = models.CharField(max_length=300, null=True, blank=True, verbose_name=_('repository path'), help_text=_('Enter local, absolute Mercurial repository path'))
    # reverse generic relation - for convenience
    permissions = generic.GenericRelation(ObjectPermission, verbose_name=_('permissions'))
    objects = ProjectManager()

    class Meta:
        verbose_name = _('project')
        verbose_name_plural = _('projects')

    def __unicode__(self):
        return unicode(self.name)

    @models.permalink
    def get_absolute_url(self):
        return ('project_detail_url', (), {'object_id': self.pk})

class Version(TimeStampedModel):
    name = models.CharField(max_length=50, verbose_name=_('name'))
    start_date = models.DateTimeField(verbose_name=_('start date'))
    due_date = models.DateTimeField(verbose_name=_('deadline'))
    is_closed = models.BooleanField(default=False, verbose_name=_('is closed?'))
    project = models.ForeignKey(Project)

    class Meta:
        verbose_name = _('version')
        verbose_name_plural = _('versions')

    def __unicode__(self):
        return unicode(self.name)

class Status(TimeStampedModel):
    name = models.CharField(max_length=50, verbose_name=_('name'))
    is_closed = models.BooleanField(default=False, verbose_name=_('is closed?'))

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _('status')
        verbose_name_plural = _('statuses')

class Priority(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('name'))
    value = models.SmallIntegerField(verbose_name=_('value'))

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _('priority')
        verbose_name_plural = _('priorities')

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('name'))

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __unicode__(self):
        return unicode(self.name)

class Ticket(TimeStampedModel):
    title = models.CharField(max_length=300, verbose_name=_('title'))
    description = models.TextField(verbose_name=_('description'))
    version = models.ForeignKey(Version,blank=True,null=True)
    status = models.ForeignKey(Status,blank=True,null=True)
    priority = models.ForeignKey(Priority,blank=True,null=True)
    project = models.ForeignKey(Project)
    author = models.ForeignKey(User, related_name="created_tickets")
    workers = models.ManyToManyField(User, related_name=_("tickets"),blank=True)
    related = models.ManyToManyField("self",through="RelatedTickets",symmetrical=False,blank=True)
    category = models.ForeignKey(Category,blank=True,null=True)
    observers = models.ManyToManyField(User, related_name=_('observed_tickets'), blank=True, null=True)

    class Meta:
        verbose_name = _('ticket')
        verbose_name_plural = _('tickets')

    def __unicode__(self):
        return unicode(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('ticket_detail_url', (), {'project_id': self.project.pk, 'object_id': self.pk})

    def send_mails(self, action):
        current_site = Site.objects.get_current()
        url =  '%s%s' % (current_site, self.get_absolute_url())
        d = Context({'url':url, 'title':self.title, 'content':self.description})
        subject = render_to_string('core/ticket_%s_subject.txt' % action, {'title':self.title}).replace('\n', '')
        message = render_to_string('core/ticket_%s_message.html' % action, d)
        recipients = []
        recipients.append(self.author.email)
        recipients.extend([user.email for user in self.observers.all()])
        recipients.extend([user.email for user in self.workers.all()])
        recipients = list(set(recipients))
        from_email = settings.DEFAULT_FROM_EMAIL
        msg = EmailMessage(subject, message, from_email, recipients)
        msg.content_subtype = 'html'
        msg.send()


class RelatedTickets(models.Model):
    first = models.ForeignKey(Ticket,related_name=_("first_set"))
    second = models.ForeignKey(Ticket,related_name=_("second_set"))
    RELATION_CHOICES = (
            ('D',_('duplicates')),
            ('B',_('is blocked by')),
            ('R',_('is related to')),
            ) 
    relation = models.CharField(max_length=1,choices=RELATION_CHOICES)


class Role(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('name'))

    def __unicode__(self):
        return unicode(self.name)

class News(TimeStampedModel):
    title = models.CharField(max_length=300, verbose_name=_('title'))
    content = models.TextField(verbose_name=_('content'))
    project = models.ForeignKey(Project)
    author = models.ForeignKey(User)

    class Meta:
        verbose_name = _('news')
        verbose_name_plural = _('news')

    def __unicode__(self):
        return unicode(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('news_detail_url', (),  {'project_id' : self.project.pk, 'object_id' : self.pk})

core/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from core.models import Project, Ticket, News, RelatedTickets
from django import forms

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ('members')

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        exclude = ('project','author','related')

    def __init__(self, *args, **kwargs):
        project = kwargs.pop('parent_project', None)
        super(TicketForm, self).__init__(*args, **kwargs)

        if project is not None:
            self.fields['version'].queryset = project.version_set


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        exclude=('project','author')

class RelatedTicketsForm(forms.ModelForm):
    class Meta:
        model=RelatedTickets
        exclude=('first')

templates/core/_project_menu.html
{% load i18n %}
{% load object_permissions %}

<h4>{% trans "Menu" %}</h4>
{% has_object_permission user change project as can_change_project %}
<table>
	<tr>
		<td>
			<a href="{% url news_url project.pk %}">{% trans _("News") %}</a>
		</td>
		<td>
			{% if can_change_project %}
				<a href="{% url add_news_url project.pk %}">{% trans _('Add news') %}</a>
			{% endif %}
		</td>
	</tr>
	<tr>
		<td>
			<a href="{{  project.get_absolute_url }}">{% trans _("Tickets") %}</a>
		</td>
		<td>
			{% if can_change_project %}
				<a href="{% url add_ticket_url project.pk %}">{% trans _("Create ticket") %}</a>
			{% endif %}
		</td>
	</tr>
		{% if project.repository_path %}
		<td>
			<a href="{% url project_repository_url project.pk %}">{% trans "Show repo log" %}</a>
		</td>
		<td></td>
		{% endif %}
	</tr>
</table>

templates/core/add_news.html
{% extends "base.html" %}
{% load i18n project_menu %}

{% block content %}
<h3>{% trans 'Add news' %}</h3>
<p>

<form method = "post" action="{% url add_news_url object_id=project.pk%}">
	{{ nform.non_field_errors }}
	<table>
		<tr>
			<td>
				{{ nform.title.errors }}
				<label for="id_title">{% trans "Title" %}:</label>
			</td>
		</tr>
		<tr>
			<td>	
				{{ nform.title }}
			</td>
		</tr>
		<tr>
			<td>
				{{ nform.content.errors }}
				<label for="id_content">{% trans 'Content' %}:</label>
			</td>
		</tr>
		<tr>
			<td>
				{{ nform.content }}
			</td>
		</tr>
		<tr>
			<td>
				{% csrf_token %}
				<input type="submit" class="formbutton" value="{% trans 'Create it!' %}">
			</td>
		</tr>
	</table>
</form>
</p>


{% endblock %}

{% block sidebar %}

{% project_menu project user %}
{% endblock %}

templates/core/add_ticket.html
{% extends "base.html" %}
{% load i18n %}
{% load project_menu %}


{% block content %}

<h3>{% trans _('Add new ticket') %}</h3>
<p>


{% if ticket_id %}
	{% url update_ticket_url project_id=project.pk object_id=ticket_id as add_or_update_ticket_url %}
{% else %}
	{% url add_ticket_url object_id=project.pk as add_ticket %}
{% endif %}
<form method = "post" action="{{ add_or_update_ticket_url }}">	
	
	<table>
		<tr>
			<td>
				{{ tform.title.errors }}
				<label for="id_title">{% trans _('Title') %}:</label>
			</td>
		</tr>
		<tr>
			<td>
				{{ tform.title }}
			</td>
		</tr>
		<tr>
			<td>
				{{ tform.description.errors }}
				<label for="id_description">{% trans _('Description') %}:</label>
			</td>
		</tr>
		<tr>
			<td>
				{{ tform.description }}
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				<label for="id_version">{% trans _('Version') %}:</label>
			</td>
			<td>
				{{ tform.version }}
			</td>
			<td>
				<label for="id_status">{% trans _('Status') %}:</label>
			</td>
			<td>
				{{ tform.status }}
			</td>
		</tr>
		<tr>
			<td>
				<label for="id_priority">{% trans _('Priority') %}:</label>
			</td>
			<td>
				{{ tform.priority }}
			</td>
			<td>
				<label for="id_workers">{% trans _('Assigned to') %}:</label>
			</td>
			<td>
				{{ tform.workers }}
			</td>
		</tr>
		<tr>
			<td>
				<label for="id_category">{% trans _('Category') %}:</label>
			</td>
			<td>
				{{ tform.category }}
			</td>
			<td>
				<label for="id_category">{% trans _('Observers') %}:</label>
			</td>
			<td>
				{{ tform.observers }}
			</td>
		</tr>
		<tr>
			<td>
				{% csrf_token %}
				<input type="submit" class="formbutton" value="Create it!">
			</td>
		</tr>

	</table>

</form>
</p>


{% endblock %}

{% block sidebar %}
{% project_menu project user %}
{% endblock %}


templates/core/attachment_list.html
{% load i18n %}
{% load pagination_tags %}
{% load attachments_tags %}

{% autopaginate attachments %}
{% paginate %}

<table>
	{% for attachment in attachments %}
	<tr>
		<td>
			<a href="/{{ attachment.attachment_file.url }}">{{ attachment.filename }}</a>
		</td>
		<td>
			{% attachment_delete_link attachment %}
		</td>
	</tr>
	{% endfor %}
</table>

templates/core/comment_list.html
{% load comments %}
{% load i18n %}

{% for comment in comment_list %}
<div class="comment">
	<div class="content">
		{{comment.comment}}
	</div>
	<br/>
	<div class="author">
		{% trans "Posted by" %} {{comment.user_name}} {{comment.submit_date|timesince }} {% trans "ago" %}.
	</div>
</div>


{% endfor %}

templates/core/files_list.html
{% extends "base.html" %}
{% load sorting_tags %}
{% load pagination_tags %}
{% load i18n %}
{% load project_menu %}

{% block content %}
<h3>{% trans _('Files') %}</h3>
<p>

{% include 'core/attachment_list.html' %}

</p>


{% endblock %}

{% block sidebar %}
{% project_menu project user %}
{% endblock %}


templates/core/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h3>Czym jest Zabaglione?</h3>
<br/>
<p>
Zabaglione to pierwszy bugtracker w całości napisany w Django.
<br/>
I tutaj dalej opis.
</p>


{% endblock %}

{% block sidebar %}

{% endblock %}


templates/core/news_detail.html
{% extends "base.html" %}
{% load comments %}
{% load markup %}
{% load i18n %}
{% load project_menu %}
{% load attachments_tags %}

{% get_attachments_for news %}

{% block content %}

<div id="news">
	<span class="title">{{news.title}}</span>
	<pre>{{news.content|markdown:'codehilite'}}</pre>
	<span class="news_author">{% trans "Posted by" %} {{news.author }} {{news.created|timesince}} {% trans "ago" %}<br/></span>
</div>
<p>
{% if attachments %}
{% include 'core/attachment_list.html' %}
{% endif %}

{% attachment_form news %}

</p>

<p>
{% get_comment_list for news as comment_list %}
{% include 'core/comment_list.html' %}

{% get_comment_form for news as form %}
{% url news_detail_url news.project.pk news.pk as next_step_url %}
{% include 'core/comment_form.html' %}
</p>

{% endblock %}

{% block sidebar %}
{% project_menu news.project user %}
{% endblock %}

templates/core/news_list.html
{% extends "base.html" %}
{% load markup %}
{% load i18n %}
{% load pagination_tags %}
{% load project_menu %}

{% block content %}
<h3>{% trans _('News') %}</h3>
<p>
{% autopaginate news 5 %}
{% paginate %}

<table>
	{% for msg in news %}
	<tr>
		<td>
			<br/>
			<span style="font-size: large;"><a href="{{ msg.get_absolute_url }}">{{msg.title}}</a></span><br/>
			<pre><div class="news_content">{{ msg.content|markdown:'codehilite' }}</div></pre><br/>
			<div class="news_author">{% trans "Posted by" %} {{ msg.author }} {{ msg.created|timesince }} {% trans "ago" %}</div>
			<br/>
		</td>
	</tr>
	{% endfor %}
</table>
{% paginate %}

</p>

{% endblock %}

{% block sidebar %}
{% project_menu project user %}
{% endblock %}


templates/core/project_detail.html
{% extends "base.html" %}
{% load sorting_tags %}
{% load pagination_tags %}
{% load i18n %}
{% load project_menu %}



{% block content %}

<h3>{{project.name}}</h3>
<p>

<table id="ticket_list">	
	<tr><th>{% anchor created ID %}</th><th>{% anchor title Title %}</th><th>{% anchor priority Priority %}</th><th>{% anchor version Version %}</th><th>{% anchor category Category %}</th><th>{% anchor status Status %}</th></tr>
	{% autosort tickets %}
	{% autopaginate tickets 10 %}
	{% paginate %}
	{% for ticket in tickets %}
	<tr class="ticket_isclosed_{{ticket.status.is_closed}}">

		<td>
			{{ticket.pk}}
		</td>
		<td><span class="{{ticket.priority|lower}}"><a href="{% url ticket_detail_url project.pk ticket.pk %}" >{{ ticket.title }}</a></span></td><td>{{ticket.priority}}</td><td>{{ticket.version}}</td><td>{{ticket.category}}</td><td>{{ticket.status}}</td>
	</tr>
	{% endfor %}
</table>
{% paginate %}

</p>

{% endblock %}

{% block sidebar %}

<h4>{% trans "Description" %}</h4>

<div style="font-size: small; padding: 10px">
	{{project.description }}
</div>

{% project_menu project user%}

{% endblock %}


templates/core/project_list.html
{% extends "base.html" %}
{% load sorting_tags %}
{% load pagination_tags %}
{% load i18n %}

{% block content %}
<h3>{% trans _('Projects') %}</h3>
<p>

{% autosort projects %}
{% autopaginate projects %}
{% paginate %}


<table>
	<tr><th>{% anchor name Name %}</th><th>{% anchor created Created %}</th></tr>
	{% for project in projects %}
	<tr>
		<td><a href="{% url project_detail_url project.pk %}">{{ project.name }}</a></td><td>{{project.created}}</td>
	</tr>
	{% endfor %}
</table>
{% paginate %}

</p>


{% endblock %}

{% block sidebar %}
<h4>{% trans _('Latest news') %}</h4>
	{% for news in latest_news %}
	<div style="border-bottom: 1px solid grey; font-size: small; padding: 10px;">
		<a href="{{news.get_absolute_url}}">{{news.title }}</a><br/>
		{{news.created|timesince}} {% trans "ago" %} <br/>
		in {{news.project}}
	</div>
	{% endfor %}
{% endblock %}


templates/core/project_repository.html
{% extends "base.html" %}
{% load i18n %}
{% load attachments_tags %}
{% load pagination_tags %}
{% load project_menu %}

{% autopaginate log %}
{% paginate %}
{% block content %}

{% for entry in log %}
<legend>
    <p>
        {{ entry.0 }}
        {{ entry.1 }}
        {{ entry.2 }}
    </p>
</legend>
{% endfor %}

{% endblock %}

{% block sidebar %}
{% project_menu project user %}
{% endblock %}

templates/core/ticket_update_message.html
Ticket {{ title }} has been updated.
<a href="{{ url }}">See changes</a>

templates/core/upload_file.html
{% extends "base.html" %}
{% load i18n %}
{% load project_menu %}


{% block content %}

<h3>{% trans _('Upload new file') %}</h3>
<p>


<form method = "post" enctype="multipart/form-data" action="{{path}}">
	
	<table>
		<tr>
			<td>
				{{ form.name.errors }}
				<label for="id_name">{% trans _('Name') %}:</label>
			</td>
		</tr>
		<tr>
			<td>
				{{ form.name }}
			</td>
		</tr>
		<tr>
			<td>
				{{ form.description.errors }}
				<label for="id_description">{% trans _('Description') %}:</label>
			</td>
		</tr>
		<tr>
			<td>
				{{ form.description }}
			</td>
		</tr>
		<tr>
			<td>
				{{ form.file }}
			</td>
		</tr>

		<tr>
			<td>
				{% csrf_token %}
				<input type="submit" class="formbutton" value="Create it!">
			</td>
		</tr>

	</table>

</form>
</p>


{% endblock %}

{% block sidebar %}
{% project_menu project user %}
{% endblock %}
